/*
 * generated by Xtext
 */
package org.deltaj;

import org.deltaj.generator.DeltaJOutputConfigurationProvider;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.generator.OutputConfigurationProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeltaJRuntimeModule extends org.deltaj.AbstractDeltaJRuntimeModule {

	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return DeltaJOutputConfigurationProvider.class;
	}

	public Class<? extends OutputConfigurationProvider> bindOutputConfigurationProvider() {
		return DeltaJOutputConfigurationProvider.class;
	}
}
