/*
 * generated by Xtext
 */
package org.deltaj.scoping;

import org.deltaj.deltaj.Product;
import org.deltaj.util.DeltaJUtils;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class DeltaJScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_Feature(Product product, EReference ref) {
		return Scopes.scopeFor(DeltaJUtils.getFeatures(product));
	}
}
