package org.deltaj.typesystem.deltaj.validator;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.Check;

import com.google.inject.Inject;

import it.xtypes.runtime.AbstractTypeSystemDeclarativeValidator;
import it.xtypes.runtime.TypingJudgmentEnvironment;
import it.xtypes.typesystem.ExpressionType;

import org.deltaj.deltaj.DeltajPackage;

import org.deltaj.typesystem.deltaj.DeltaJTypeSystemDefinition;

/**
 * Automatically generated by XTypeS, http://xtypes.sourceforge.net
 * Do not modify it.
 * This class should be instantiated with Google Guide injector.
 */
public class DeltaJTypeSystemValidator
		extends
			AbstractTypeSystemDeclarativeValidator {
	@Inject
	protected DeltaJTypeSystemDefinition typeSystem;

	protected DeltajPackage basicPackage = DeltajPackage.eINSTANCE;

	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.deltaj.deltaj.DeltajPackage.eINSTANCE);
		return result;
	}

	protected ExpressionType createBasicType(String basic) {
		return typeSystem.createBasicType(basic);
	}

	protected ExpressionType createEClassifierType(EClassifier eClassifier) {
		return typeSystem.createEClassifierType(eClassifier);
	}

	protected ExpressionType createCollectionType(ExpressionType expressionType) {
		return typeSystem.createCollectionType(expressionType);
	}

}
