/*
 * generated by Xtext
 */
package org.deltaj.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DeltaJExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.deltaj.ui.internal.DeltaJActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.deltaj.ui.internal.DeltaJActivator.getInstance().getInjector("org.deltaj.DeltaJ");
	}
	
}
