/*
 * generated by Xtext
 */
package org.deltaj.ui;

import org.deltaj.ui.outline.DeltaJOutlinePage;
import org.deltaj.ui.wizard.DeltaJNewProjectCreator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.ui.views.contentoutline.IContentOutlinePage;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DeltaJUiModule extends org.deltaj.ui.AbstractDeltaJUiModule {
	public DeltaJUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return DeltaJNewProjectCreator.class;
	}

	@Override
	public Class<? extends IContentOutlinePage> bindIContentOutlinePage() {
		return DeltaJOutlinePage.class;
	}
	
	public Class bindIXtextEditorCallback() { 
		return org.eclipse.xtext.builder.nature.NatureAddingEditorCallback.class;
	}
}
