/*
* generated by Xtext
*/
package org.deltaj.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.deltaj.services.DeltaJGrammarAccess;

public class DeltaJParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DeltaJGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.deltaj.parser.antlr.internal.InternalDeltaJParser createParser(XtextTokenStream stream) {
		return new org.deltaj.parser.antlr.internal.InternalDeltaJParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public DeltaJGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DeltaJGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
