/**
 * generated by Xtext
 */
package org.deltaj.generator;

import com.google.common.collect.Iterables;
import com.google.inject.Inject;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import org.deltaj.deltaj.AndOrExpression;
import org.deltaj.deltaj.ArithmeticSigned;
import org.deltaj.deltaj.Assignment;
import org.deltaj.deltaj.BasicType;
import org.deltaj.deltaj.BoolConstant;
import org.deltaj.deltaj.BooleanNegation;
import org.deltaj.deltaj.Cast;
import org.deltaj.deltaj.ClassType;
import org.deltaj.deltaj.Comparison;
import org.deltaj.deltaj.Expression;
import org.deltaj.deltaj.ExpressionStatement;
import org.deltaj.deltaj.Field;
import org.deltaj.deltaj.FieldSelection;
import org.deltaj.deltaj.IfStatement;
import org.deltaj.deltaj.IntConstant;
import org.deltaj.deltaj.JavaVerbatim;
import org.deltaj.deltaj.LocalVariableDeclaration;
import org.deltaj.deltaj.Message;
import org.deltaj.deltaj.Method;
import org.deltaj.deltaj.MethodCall;
import org.deltaj.deltaj.Minus;
import org.deltaj.deltaj.MultiOrDiv;
import org.deltaj.deltaj.New;
import org.deltaj.deltaj.Null;
import org.deltaj.deltaj.Original;
import org.deltaj.deltaj.Parameter;
import org.deltaj.deltaj.Paren;
import org.deltaj.deltaj.Plus;
import org.deltaj.deltaj.Product;
import org.deltaj.deltaj.ReturnStatement;
import org.deltaj.deltaj.Selection;
import org.deltaj.deltaj.Statement;
import org.deltaj.deltaj.StatementBlock;
import org.deltaj.deltaj.StringConstant;
import org.deltaj.deltaj.This;
import org.deltaj.deltaj.Type;
import org.deltaj.deltaj.VariableAccess;
import org.deltaj.deltaj.VoidType;
import org.deltaj.util.ClassCollection;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class DeltaJGenerator implements IGenerator {
  @Inject
  @Extension
  private DeltaJGeneratorExtensions generatorExtensions;

  @Inject
  private DeltaJConstraintsGenerator constraintsGenerator;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    Iterable<Product> _filter = Iterables.<Product>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Product.class);
    for (final Product product : _filter) {
      this.compile(product, fsa);
    }
    this.constraintsGenerator.doGenerate(resource, fsa);
  }

  public void compile(final Product product, final IFileSystemAccess fsa) {
    ClassCollection _classesToGenerate = this.generatorExtensions.classesToGenerate(product);
    for (final org.deltaj.deltaj.Class clazz : _classesToGenerate) {
      this.compile(product, clazz, fsa);
    }
  }

  public void compile(final Product product, final org.deltaj.deltaj.Class clazz, final IFileSystemAccess fsa) {
    fsa.generateFile(this.generatorExtensions.fileName(product, clazz), 
      this.compile(product, clazz));
  }

  public CharSequence compile(final Product product, final org.deltaj.deltaj.Class clazz) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _packageName = this.generatorExtensions.packageName(product);
    _builder.append(_packageName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class ");
    String _name = clazz.getName();
    _builder.append(_name);
    _builder.append(" ");
    String _extendsClause = this.extendsClause(clazz);
    _builder.append(_extendsClause);
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    {
      EList<Field> _fields = clazz.getFields();
      for(final Field f : _fields) {
        _builder.append("\t");
        CharSequence _fieldRep = this.fieldRep(f);
        _builder.append(_fieldRep, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.newLine();
    {
      EList<Method> _methods = clazz.getMethods();
      for(final Method m : _methods) {
        _builder.append("\t");
        CharSequence _methodRep = this.methodRep(m);
        _builder.append(_methodRep, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public String extendsClause(final org.deltaj.deltaj.Class clazz) {
    String _xifexpression = null;
    String _extends = clazz.getExtends();
    boolean _notEquals = (!Objects.equals(_extends, null));
    if (_notEquals) {
      String _extends_1 = clazz.getExtends();
      String _plus = ("extends " + _extends_1);
      _xifexpression = (_plus + " ");
    } else {
      _xifexpression = "";
    }
    return _xifexpression;
  }

  public CharSequence fieldRep(final Field field) {
    StringConcatenation _builder = new StringConcatenation();
    String _typeRep = this.typeRep(field.getType());
    _builder.append(_typeRep);
    _builder.append(" ");
    String _name = field.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected String _typeRep(final Type voidType) {
    return "";
  }

  protected String _typeRep(final VoidType voidType) {
    return "void";
  }

  protected String _typeRep(final BasicType basic) {
    return basic.getBasic();
  }

  protected String _typeRep(final ClassType clazz) {
    return clazz.getClassref();
  }

  public CharSequence methodRep(final Method method) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    String _typeRep = this.typeRep(method.getReturntype());
    _builder.append(_typeRep);
    _builder.append(" ");
    String _name = method.getName();
    _builder.append(_name);
    _builder.append("(");
    String _parameterList = this.parameterList(method);
    _builder.append(_parameterList);
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    {
      StatementBlock _body = method.getBody();
      boolean _notEquals = (!Objects.equals(_body, null));
      if (_notEquals) {
        _builder.append("\t");
        CharSequence _bodyRep = this.bodyRep(method.getBody());
        _builder.append(_bodyRep, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }

  public String parameterList(final Method m) {
    final Function1<Parameter, String> _function = (Parameter p) -> {
      String _typeRep = this.typeRep(p.getType());
      String _plus = (_typeRep + " ");
      String _name = p.getName();
      return (_plus + _name);
    };
    return IterableExtensions.join(ListExtensions.<Parameter, String>map(m.getParams(), _function), ", ");
  }

  public CharSequence bodyRep(final StatementBlock body) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<LocalVariableDeclaration> _localvariables = body.getLocalvariables();
      for(final LocalVariableDeclaration localvars : _localvariables) {
        String _typeRep = this.typeRep(localvars.getType());
        _builder.append(_typeRep);
        _builder.append(" ");
        String _name = localvars.getName();
        _builder.append(_name);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      EList<Statement> _statements = body.getStatements();
      for(final Statement statement : _statements) {
        CharSequence _compileStatement = this.compileStatement(statement);
        _builder.append(_compileStatement);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _compileStatement(final ExpressionStatement expressionStatement) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _compileExp = this.compileExp(expressionStatement.getExpression());
    _builder.append(_compileExp);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileStatement(final ReturnStatement returnStmt) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("return ");
    {
      Expression _expression = returnStmt.getExpression();
      boolean _notEquals = (!Objects.equals(_expression, null));
      if (_notEquals) {
        CharSequence _compileExp = this.compileExp(returnStmt.getExpression());
        _builder.append(_compileExp);
      }
    }
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileStatement(final JavaVerbatim javaVerbatim) {
    return this.generatorExtensions.extractJavaVerbatimCode(javaVerbatim);
  }

  protected CharSequence _compileStatement(final Assignment assignment) {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _compileExp = this.compileExp(assignment.getLeft());
    _builder.append(_compileExp);
    _builder.append(" = ");
    CharSequence _compileExp_1 = this.compileExp(assignment.getRight());
    _builder.append(_compileExp_1);
    _builder.append(";");
    return _builder;
  }

  protected CharSequence _compileStatement(final IfStatement ifStatement) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("if (");
    CharSequence _compileExp = this.compileExp(ifStatement.getExpression());
    _builder.append(_compileExp);
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    Object _bodyRep = this.bodyRep(ifStatement.getThenBlock());
    _builder.append(_bodyRep, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    {
      StatementBlock _elseBlock = ifStatement.getElseBlock();
      boolean _notEquals = (!Objects.equals(_elseBlock, null));
      if (_notEquals) {
        _builder.append(" else {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        Object _bodyRep_1 = this.bodyRep(ifStatement.getElseBlock());
        _builder.append(_bodyRep_1, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("}");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileExp(final Expression expression) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("// ");
    String _name = expression.eClass().getName();
    _builder.append(_name);
    _builder.append(" generation not yet implemented");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileExp(final Plus plus) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(plus.getLeft());
    _builder.append(_compileExp);
    _builder.append(" + ");
    Object _compileExp_1 = this.compileExp(plus.getRight());
    _builder.append(_compileExp_1);
    return _builder;
  }

  protected CharSequence _compileExp(final Minus minus) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(minus.getLeft());
    _builder.append(_compileExp);
    _builder.append(" - ");
    Object _compileExp_1 = this.compileExp(minus.getRight());
    _builder.append(_compileExp_1);
    return _builder;
  }

  protected CharSequence _compileExp(final MultiOrDiv exp) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(exp.getLeft());
    _builder.append(_compileExp);
    _builder.append(" ");
    String _op = exp.getOp();
    _builder.append(_op);
    _builder.append(" ");
    Object _compileExp_1 = this.compileExp(exp.getRight());
    _builder.append(_compileExp_1);
    return _builder;
  }

  protected CharSequence _compileExp(final Comparison exp) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(exp.getLeft());
    _builder.append(_compileExp);
    _builder.append(" ");
    String _op = exp.getOp();
    _builder.append(_op);
    _builder.append(" ");
    Object _compileExp_1 = this.compileExp(exp.getRight());
    _builder.append(_compileExp_1);
    return _builder;
  }

  protected CharSequence _compileExp(final AndOrExpression exp) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(exp.getLeft());
    _builder.append(_compileExp);
    _builder.append(" ");
    String _op = exp.getOp();
    _builder.append(_op);
    _builder.append(" ");
    Object _compileExp_1 = this.compileExp(exp.getRight());
    _builder.append(_compileExp_1);
    return _builder;
  }

  protected CharSequence _compileExp(final BooleanNegation exp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("!");
    Object _compileExp = this.compileExp(exp.getExpression());
    _builder.append(_compileExp);
    return _builder;
  }

  protected CharSequence _compileExp(final ArithmeticSigned exp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("-(");
    Object _compileExp = this.compileExp(exp.getExpression());
    _builder.append(_compileExp);
    _builder.append(")");
    return _builder;
  }

  protected CharSequence _compileExp(final This thiz) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("this");
    return _builder;
  }

  protected CharSequence _compileExp(final Null nul) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("null");
    return _builder;
  }

  protected CharSequence _compileExp(final Original original) {
    StringConcatenation _builder = new StringConcatenation();
    String _method = original.getMethod();
    _builder.append(_method);
    _builder.append("(");
    String _compileArgs = this.compileArgs(original.getArgs());
    _builder.append(_compileArgs);
    _builder.append(")");
    return _builder;
  }

  protected CharSequence _compileExp(final IntConstant c) {
    StringConcatenation _builder = new StringConcatenation();
    int _constant = c.getConstant();
    _builder.append(_constant);
    return _builder;
  }

  protected CharSequence _compileExp(final StringConstant c) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\"");
    String _constant = c.getConstant();
    _builder.append(_constant);
    _builder.append("\"");
    return _builder;
  }

  protected CharSequence _compileExp(final BoolConstant c) {
    StringConcatenation _builder = new StringConcatenation();
    String _constant = c.getConstant();
    _builder.append(_constant);
    return _builder;
  }

  protected CharSequence _compileExp(final VariableAccess variable) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = variable.getVariable().getName();
    _builder.append(_name);
    return _builder;
  }

  protected CharSequence _compileExp(final New n) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new ");
    String _class_ = n.getClass_();
    _builder.append(_class_);
    _builder.append("()");
    return _builder;
  }

  protected CharSequence _compileExp(final Cast cast) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    String _type = cast.getType();
    _builder.append(_type);
    _builder.append(") ");
    Object _compileExp = this.compileExp(cast.getObject());
    _builder.append(_compileExp);
    return _builder;
  }

  protected CharSequence _compileExp(final Paren paren) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    Object _compileExp = this.compileExp(paren.getExpression());
    _builder.append(_compileExp);
    _builder.append(")");
    return _builder;
  }

  protected CharSequence _compileExp(final Selection sel) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExp = this.compileExp(sel.getReceiver());
    _builder.append(_compileExp);
    _builder.append(".");
    CharSequence _compileMessage = this.compileMessage(sel.getMessage());
    _builder.append(_compileMessage);
    return _builder;
  }

  protected CharSequence _compileMessage(final Message message) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(" ");
    return _builder;
  }

  protected CharSequence _compileMessage(final FieldSelection field) {
    StringConcatenation _builder = new StringConcatenation();
    String _field = field.getField();
    _builder.append(_field);
    return _builder;
  }

  protected CharSequence _compileMessage(final MethodCall methodCall) {
    StringConcatenation _builder = new StringConcatenation();
    String _method = methodCall.getMethod();
    _builder.append(_method);
    _builder.append("(");
    String _compileArgs = this.compileArgs(methodCall.getArgs());
    _builder.append(_compileArgs);
    _builder.append(")");
    return _builder;
  }

  public String compileArgs(final List<Expression> args) {
    final Function1<Expression, Object> _function = (Expression arg) -> {
      return this.compileExp(arg);
    };
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(", ");
    return IterableExtensions.join(ListExtensions.<Expression, Object>map(args, _function), _builder);
  }

  @XbaseGenerated
  public String typeRep(final Type basic) {
    if (basic instanceof BasicType) {
      return _typeRep((BasicType)basic);
    } else if (basic instanceof ClassType) {
      return _typeRep((ClassType)basic);
    } else if (basic instanceof VoidType) {
      return _typeRep((VoidType)basic);
    } else if (basic != null) {
      return _typeRep(basic);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(basic).toString());
    }
  }

  @XbaseGenerated
  public CharSequence compileStatement(final Statement assignment) {
    if (assignment instanceof Assignment) {
      return _compileStatement((Assignment)assignment);
    } else if (assignment instanceof ExpressionStatement) {
      return _compileStatement((ExpressionStatement)assignment);
    } else if (assignment instanceof IfStatement) {
      return _compileStatement((IfStatement)assignment);
    } else if (assignment instanceof JavaVerbatim) {
      return _compileStatement((JavaVerbatim)assignment);
    } else if (assignment instanceof ReturnStatement) {
      return _compileStatement((ReturnStatement)assignment);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(assignment).toString());
    }
  }

  @XbaseGenerated
  public CharSequence compileExp(final Expression c) {
    if (c instanceof BoolConstant) {
      return _compileExp((BoolConstant)c);
    } else if (c instanceof IntConstant) {
      return _compileExp((IntConstant)c);
    } else if (c instanceof StringConstant) {
      return _compileExp((StringConstant)c);
    } else if (c instanceof AndOrExpression) {
      return _compileExp((AndOrExpression)c);
    } else if (c instanceof ArithmeticSigned) {
      return _compileExp((ArithmeticSigned)c);
    } else if (c instanceof BooleanNegation) {
      return _compileExp((BooleanNegation)c);
    } else if (c instanceof Cast) {
      return _compileExp((Cast)c);
    } else if (c instanceof Comparison) {
      return _compileExp((Comparison)c);
    } else if (c instanceof Minus) {
      return _compileExp((Minus)c);
    } else if (c instanceof MultiOrDiv) {
      return _compileExp((MultiOrDiv)c);
    } else if (c instanceof New) {
      return _compileExp((New)c);
    } else if (c instanceof Null) {
      return _compileExp((Null)c);
    } else if (c instanceof Original) {
      return _compileExp((Original)c);
    } else if (c instanceof Paren) {
      return _compileExp((Paren)c);
    } else if (c instanceof Plus) {
      return _compileExp((Plus)c);
    } else if (c instanceof Selection) {
      return _compileExp((Selection)c);
    } else if (c instanceof This) {
      return _compileExp((This)c);
    } else if (c instanceof VariableAccess) {
      return _compileExp((VariableAccess)c);
    } else if (c != null) {
      return _compileExp(c);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(c).toString());
    }
  }

  @XbaseGenerated
  public CharSequence compileMessage(final Message field) {
    if (field instanceof FieldSelection) {
      return _compileMessage((FieldSelection)field);
    } else if (field instanceof MethodCall) {
      return _compileMessage((MethodCall)field);
    } else if (field != null) {
      return _compileMessage(field);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(field).toString());
    }
  }
}
